#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

TERM=xterm-256color
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=/usr/local/bin:$PATH

alias pr='sudo puppet agent --onetime --verbose --no-daemonize --server puppet3.humedica.net --ca_server puppet2.humedica.net'
